menu:
  keppler_products:
    name: Products
    current: ['/']
    url_path: /
    icon: rocket
    model: KepplerProducts::Product
    environment: all
    position: 4
    submenu:
      - cotization:
          name: cotization
          url_path: /admin/products/cotizations
          icon: layers
          current: ['/admin/products/cotizations']
          model: KepplerProducts::Cotization

      - product:
          name: product
          url_path: /admin/products/products
          icon: layers
          current: ['/admin/products/products']
          model: KepplerProducts::Product

      - category:
          name: category
          url_path: /admin/products/categories
          icon: layers
          current: ['/admin/products/categories']
          model: KepplerProducts::Category

      # - new:
      #     name: + Add new module
      #     url_path: /url_path
      #     current: ['/current_path']
      #     enviroment: development
      #     model: User
