modules:
  catalogues:
    name: Catalogue
    model: KepplerProductsCatalogue
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  cotizations:
    name: Cotization
    model: KepplerProductsCotization
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  products:
    name: Product
    model: KepplerProductsProduct
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  categories:
    name: Category
    model: KepplerProductsCategory
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]
