menu:
  keppler_banners:
    name: Banner
    current: ['/admin/banners/banners']
    url_path: /admin/banners/banners
    icon: rocket
    model: KepplerBanners::Banner
    environment: all
    position: 4
    submenu:

      # - new:
      #     name: + Add new module
      #     url_path: /url_path
      #     current: ['/current_path']
      #     enviroment: development
      #     model: User
